name: ubiiqueso
description: "A Fullqueso project."

version: 3.2.3+24

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  blinking_text: ^1.0.4
  cached_network_image: ^3.4.1
  cloud_firestore: ^5.6.7
  cupertino_icons: ^1.0.8
  firebase_auth: ^5.5.3
  firebase_core: ^3.13.0
  firebase_database: ^11.3.5
  flutter_masked_text2: ^0.9.1
  flutter_spinkit: ^5.2.1
  font_awesome_flutter: ^10.7.0
  http: ^1.1.0
  intl: ^0.19.0
  package_info_plus: ^8.1.1
  shared_preferences: ^2.2.2
  timeago: ^3.3.0
  url_launcher: ^6.2.5
  firebase_crashlytics: ^4.3.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  flutter_native_splash: ^2.4.0
  change_app_package_name: ^1.5.0

# flutter clean && flutter pub get && flutter pub run flutter_native_splash:create
flutter_native_splash:
  color: "#FE0019"
  image: assets/images/splash.png
  android_12:
    image: assets/images/splash.png
  fullscreen: true
  android: true
  web: false
  ios: false

flutter:

  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-Thin.ttf
          weight: 100
        - asset: assets/fonts/Montserrat/Montserrat-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Montserrat/Montserrat-Light.ttf
          weight: 300
        - asset: assets/fonts/Montserrat/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat/Montserrat-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Montserrat/Montserrat-Black.ttf
          weight: 900

